### ISSUE TITLE
API Urls with CamelCase names ?

### ISSUE THREAD

**Issue by rvsoni** [CycloneDX/cyclonedx-bom-repo-server#166]
Is there any reason to make Urls with CamelCase names?

Like

/Bom
/BomExchange
/Search

![Selection_497](https://user-images.githubusercontent.com/4734787/169707482-172ab3e6-80e4-497f-b704-e80ed790197c.png)

**Comment by coderpatros** [comment]
It's just the framework default. I should probably override it. But the paths are not case sensitive.

**Comment by rvsoni** [comment]
@coderpatros 

Thansk for the quick respinse,
