### ISSUE TITLE
Does someone maintain this project

### ISSUE THREAD

**Issue by angegar** [CycloneDX/cyclonedx-bom-repo-server#379]
Hi there, 
I am looking for a bom storage solution. I like this small server but i am afraid because the latest commit was 1 year ago. Can someone tell me if this project is alive ?

Regards

**Comment by stevespringett** [comment]
Yes, the project is still alive. There's a bit of a chicken/egg issue affecting this project. We're working on defining https://github.com/CycloneDX/cyclonedx-bom-exchange-api which this repo, the bom-repo-server, implements. Once the exchange API gets flushed out more, that will lead to additional work for this project.

**Comment by angegar** [comment]
Thank you very much, thus I will be spend more time trying to make the search api work. Then, i will use it prod ;)

Thank you for all the work about secure supply chain. It helps a lot.

**Comment by angegar** [comment]
BTW, do you have some advise to implement a permission mechanism in front of the server ?

I would like to prevent anyone to delete some sboms ;)
