### ISSUE TITLE
Add support for arm64 processors

### ISSUE THREAD

**Issue by stevespringett** [CycloneDX/cyclonedx-bom-repo-server#67]
The Dockerfile uses a base image that supports x86_64 only. This should be updated to use a base image that is multi-arch.

Related to:
* https://github.com/DependencyTrack/dependency-track/issues/877
* https://github.com/DependencyTrack/dependency-track/issues/1213

**Comment by k3rnelpan1c-dev** [comment]
Just a side note the `mcr.microsoft.com/dotnet/aspnet` does offer `arm64`, `arm32` and `amd64` architectures, the CI however only builds `amd64` as far as I can tell.

**Comment by coderpatros** [comment]
This should be resolved by #76. I can't test it myself. So if there are any issues running it please re-open this issue.
